### ISSUE TITLE
using std::string as base string or Qstring

### ISSUE THREAD

**Issue by Wuqiqi123** [RobSimulatorGroup/gobot#13]

**Comment by StephenYu-R** [comment]
It seems that inheriting from std::string as a base class is dangerous since the design of std::string doesn't allow users to override the built-in methods and it's not meant to leave virtual functions to users. 

Instead, a decent way is to develop a custom string type converting from std::string like QString and Godot::string, both of which implement customized char type and string type.

In convenience, QString could be used as a temporary tool.
